/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsWebsitesPortalsAppsRouteImport } from './routes/solutions.websites-portals-apps'
import { Route as SolutionsProjectIntelligenceRouteImport } from './routes/solutions.project-intelligence'
import { Route as SolutionsBusinessMediaRouteImport } from './routes/solutions.business-media'
import { Route as SolutionsAiAssistantsRouteImport } from './routes/solutions.ai-assistants'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsWebsitesPortalsAppsRoute =
  SolutionsWebsitesPortalsAppsRouteImport.update({
    id: '/websites-portals-apps',
    path: '/websites-portals-apps',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsProjectIntelligenceRoute =
  SolutionsProjectIntelligenceRouteImport.update({
    id: '/project-intelligence',
    path: '/project-intelligence',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsBusinessMediaRoute = SolutionsBusinessMediaRouteImport.update({
  id: '/business-media',
  path: '/business-media',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsAiAssistantsRoute = SolutionsAiAssistantsRouteImport.update({
  id: '/ai-assistants',
  path: '/ai-assistants',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/solutions/ai-assistants': typeof SolutionsAiAssistantsRoute
  '/solutions/business-media': typeof SolutionsBusinessMediaRoute
  '/solutions/project-intelligence': typeof SolutionsProjectIntelligenceRoute
  '/solutions/websites-portals-apps': typeof SolutionsWebsitesPortalsAppsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/solutions/ai-assistants': typeof SolutionsAiAssistantsRoute
  '/solutions/business-media': typeof SolutionsBusinessMediaRoute
  '/solutions/project-intelligence': typeof SolutionsProjectIntelligenceRoute
  '/solutions/websites-portals-apps': typeof SolutionsWebsitesPortalsAppsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/solutions/ai-assistants': typeof SolutionsAiAssistantsRoute
  '/solutions/business-media': typeof SolutionsBusinessMediaRoute
  '/solutions/project-intelligence': typeof SolutionsProjectIntelligenceRoute
  '/solutions/websites-portals-apps': typeof SolutionsWebsitesPortalsAppsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/solutions'
    | '/terms'
    | '/solutions/ai-assistants'
    | '/solutions/business-media'
    | '/solutions/project-intelligence'
    | '/solutions/websites-portals-apps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/solutions'
    | '/terms'
    | '/solutions/ai-assistants'
    | '/solutions/business-media'
    | '/solutions/project-intelligence'
    | '/solutions/websites-portals-apps'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/solutions'
    | '/terms'
    | '/solutions/ai-assistants'
    | '/solutions/business-media'
    | '/solutions/project-intelligence'
    | '/solutions/websites-portals-apps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  PrivacyRoute: typeof PrivacyRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/websites-portals-apps': {
      id: '/solutions/websites-portals-apps'
      path: '/websites-portals-apps'
      fullPath: '/solutions/websites-portals-apps'
      preLoaderRoute: typeof SolutionsWebsitesPortalsAppsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/project-intelligence': {
      id: '/solutions/project-intelligence'
      path: '/project-intelligence'
      fullPath: '/solutions/project-intelligence'
      preLoaderRoute: typeof SolutionsProjectIntelligenceRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/business-media': {
      id: '/solutions/business-media'
      path: '/business-media'
      fullPath: '/solutions/business-media'
      preLoaderRoute: typeof SolutionsBusinessMediaRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/ai-assistants': {
      id: '/solutions/ai-assistants'
      path: '/ai-assistants'
      fullPath: '/solutions/ai-assistants'
      preLoaderRoute: typeof SolutionsAiAssistantsRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsAiAssistantsRoute: typeof SolutionsAiAssistantsRoute
  SolutionsBusinessMediaRoute: typeof SolutionsBusinessMediaRoute
  SolutionsProjectIntelligenceRoute: typeof SolutionsProjectIntelligenceRoute
  SolutionsWebsitesPortalsAppsRoute: typeof SolutionsWebsitesPortalsAppsRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsAiAssistantsRoute: SolutionsAiAssistantsRoute,
  SolutionsBusinessMediaRoute: SolutionsBusinessMediaRoute,
  SolutionsProjectIntelligenceRoute: SolutionsProjectIntelligenceRoute,
  SolutionsWebsitesPortalsAppsRoute: SolutionsWebsitesPortalsAppsRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  PrivacyRoute: PrivacyRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
