/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceIntakeRouteImport } from './routes/voice-intake'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SmsConsentRouteImport } from './routes/sms-consent'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsWebsitesPortalsAppsRouteImport } from './routes/solutions.websites-portals-apps'
import { Route as SolutionsProjectIntelligenceRouteImport } from './routes/solutions.project-intelligence'
import { Route as SolutionsBusinessMediaRouteImport } from './routes/solutions.business-media'
import { Route as SolutionsAiAssistantsRouteImport } from './routes/solutions.ai-assistants'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminIntakeRouteImport } from './routes/admin.intake'

const VoiceIntakeRoute = VoiceIntakeRouteImport.update({
  id: '/voice-intake',
  path: '/voice-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsConsentRoute = SmsConsentRouteImport.update({
  id: '/sms-consent',
  path: '/sms-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsWebsitesPortalsAppsRoute =
  SolutionsWebsitesPortalsAppsRouteImport.update({
    id: '/websites-portals-apps',
    path: '/websites-portals-apps',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsProjectIntelligenceRoute =
  SolutionsProjectIntelligenceRouteImport.update({
    id: '/project-intelligence',
    path: '/project-intelligence',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsBusinessMediaRoute = SolutionsBusinessMediaRouteImport.update({
  id: '/business-media',
  path: '/business-media',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsAiAssistantsRoute = SolutionsAiAssistantsRouteImport.update({
  id: '/ai-assistants',
  path: '/ai-assistants',
  getParentRoute: () => SolutionsRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntakeRoute = AdminIntakeRouteImport.update({
  id: '/admin/intake',
  path: '/admin/intake',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/sms-consent': typeof SmsConsentRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/voice-intake': typeof VoiceIntakeRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/login': typeof AdminLoginRoute
  '/solutions/ai-assistants': typeof SolutionsAiAssistantsRoute
  '/solutions/business-media': typeof SolutionsBusinessMediaRoute
  '/solutions/project-intelligence': typeof SolutionsProjectIntelligenceRoute
  '/solutions/websites-portals-apps': typeof SolutionsWebsitesPortalsAppsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/sms-consent': typeof SmsConsentRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/voice-intake': typeof VoiceIntakeRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/login': typeof AdminLoginRoute
  '/solutions/ai-assistants': typeof SolutionsAiAssistantsRoute
  '/solutions/business-media': typeof SolutionsBusinessMediaRoute
  '/solutions/project-intelligence': typeof SolutionsProjectIntelligenceRoute
  '/solutions/websites-portals-apps': typeof SolutionsWebsitesPortalsAppsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/privacy': typeof PrivacyRoute
  '/sms-consent': typeof SmsConsentRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/voice-intake': typeof VoiceIntakeRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/login': typeof AdminLoginRoute
  '/solutions/ai-assistants': typeof SolutionsAiAssistantsRoute
  '/solutions/business-media': typeof SolutionsBusinessMediaRoute
  '/solutions/project-intelligence': typeof SolutionsProjectIntelligenceRoute
  '/solutions/websites-portals-apps': typeof SolutionsWebsitesPortalsAppsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/book'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/sms-consent'
    | '/solutions'
    | '/terms'
    | '/voice-intake'
    | '/admin/intake'
    | '/admin/login'
    | '/solutions/ai-assistants'
    | '/solutions/business-media'
    | '/solutions/project-intelligence'
    | '/solutions/websites-portals-apps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/book'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/sms-consent'
    | '/solutions'
    | '/terms'
    | '/voice-intake'
    | '/admin/intake'
    | '/admin/login'
    | '/solutions/ai-assistants'
    | '/solutions/business-media'
    | '/solutions/project-intelligence'
    | '/solutions/websites-portals-apps'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/book'
    | '/contact'
    | '/how-we-work'
    | '/privacy'
    | '/sms-consent'
    | '/solutions'
    | '/terms'
    | '/voice-intake'
    | '/admin/intake'
    | '/admin/login'
    | '/solutions/ai-assistants'
    | '/solutions/business-media'
    | '/solutions/project-intelligence'
    | '/solutions/websites-portals-apps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  PrivacyRoute: typeof PrivacyRoute
  SmsConsentRoute: typeof SmsConsentRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TermsRoute: typeof TermsRoute
  VoiceIntakeRoute: typeof VoiceIntakeRoute
  AdminIntakeRoute: typeof AdminIntakeRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-intake': {
      id: '/voice-intake'
      path: '/voice-intake'
      fullPath: '/voice-intake'
      preLoaderRoute: typeof VoiceIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-consent': {
      id: '/sms-consent'
      path: '/sms-consent'
      fullPath: '/sms-consent'
      preLoaderRoute: typeof SmsConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/websites-portals-apps': {
      id: '/solutions/websites-portals-apps'
      path: '/websites-portals-apps'
      fullPath: '/solutions/websites-portals-apps'
      preLoaderRoute: typeof SolutionsWebsitesPortalsAppsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/project-intelligence': {
      id: '/solutions/project-intelligence'
      path: '/project-intelligence'
      fullPath: '/solutions/project-intelligence'
      preLoaderRoute: typeof SolutionsProjectIntelligenceRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/business-media': {
      id: '/solutions/business-media'
      path: '/business-media'
      fullPath: '/solutions/business-media'
      preLoaderRoute: typeof SolutionsBusinessMediaRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/ai-assistants': {
      id: '/solutions/ai-assistants'
      path: '/ai-assistants'
      fullPath: '/solutions/ai-assistants'
      preLoaderRoute: typeof SolutionsAiAssistantsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/intake': {
      id: '/admin/intake'
      path: '/admin/intake'
      fullPath: '/admin/intake'
      preLoaderRoute: typeof AdminIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsAiAssistantsRoute: typeof SolutionsAiAssistantsRoute
  SolutionsBusinessMediaRoute: typeof SolutionsBusinessMediaRoute
  SolutionsProjectIntelligenceRoute: typeof SolutionsProjectIntelligenceRoute
  SolutionsWebsitesPortalsAppsRoute: typeof SolutionsWebsitesPortalsAppsRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsAiAssistantsRoute: SolutionsAiAssistantsRoute,
  SolutionsBusinessMediaRoute: SolutionsBusinessMediaRoute,
  SolutionsProjectIntelligenceRoute: SolutionsProjectIntelligenceRoute,
  SolutionsWebsitesPortalsAppsRoute: SolutionsWebsitesPortalsAppsRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  PrivacyRoute: PrivacyRoute,
  SmsConsentRoute: SmsConsentRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TermsRoute: TermsRoute,
  VoiceIntakeRoute: VoiceIntakeRoute,
  AdminIntakeRoute: AdminIntakeRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
